### ISSUE TITLE
SSL handling

### ISSUE THREAD

**Issue by andor44** [RoxasShadow/rollbar-rs#11]
The crate currently uses a rather old version of `hyper-openssl`. This version of the crate is not compatible with recent versions of OpenSSL (e.g. the one that ships out of the box on newer MacOS versions). It'd make sense to bump to a newer OpenSSL version, however I think the more sensible approach would be to use `hyper-tls` which internally depends on [`native-tls`](https://crates.io/crates/native-tls) which will use the platform's native TLS stack or fall back to OpenSSL if there isn't one.

I'm up to preparing a PR for either one, I just want to know if you'd prefer bringing `hyper-openssl` up to date or going the `native-tls` route?

**Comment by RoxasShadow** [comment]
Hey @andor44, thanks for opening this issue - I am really sorry for the very late reply, for some reasons I didn't get -or I just missed it- any notification about this issue! By the way, I have just merged #12, which include `hyper-tls` as well.
