### ISSUE TITLE
Code context of reported occurrences

### ISSUE THREAD

**Issue by poroszd** [RoxasShadow/rollbar-rs#13]
Hi folks!

Rollbar engineer here, I found here via a customer of ours who found that grouping is weird.

I found that the occurrences reported by this SDK have `code` field in the stack frames that  looks like a memory address or something like that. I'm not familiar with Rust, but that field is supposed to be a snippet of the source code of that stack frame.

I'd just like to let you know that by default we take the `code` fields of all stack frames into account for fingerprinting, so if the `code` reported to Rollbar is not consistent (e.g. changes between running the same application multiple times), grouping will not really work.

**Comment by RoxasShadow** [comment]
Thanks to @ecton this issue can be considered resolved. Thank you for reporting this and keep up the good work!
